---
node_role: "validator"
litho_service_name: "lithod-mainnet-9005-val"
litho_home: "/var/lib/litho-mainnet-9005-val"

litho_p2p_port: 26656
litho_rpc_port: 26657
litho_grpc_port: 9090
litho_evm_rpc_port: 8545
litho_ws_port: 8546
litho_metrics_port: 26660
rpc_laddr: "tcp://127.0.0.1:26657"
api_address: "tcp://127.0.0.1:1317"
grpc_address: "127.0.0.1:9090"
evm_rpc_address: "127.0.0.1:8545"
evm_ws_address: "127.0.0.1:8546"
prometheus_listen_addr: "127.0.0.1:26660"

wireguard_address: "10.200.5.1"
wireguard_peers:
  - name: mainnet-sentry-01
    public_key: "{{ mainnet_sentry1_wg_public_key }}"
    endpoint: "31.97.39.146:51825"
    allowed_ips: ["10.200.5.2/32"]
    persistent_keepalive: 25
  - name: mainnet-sentry-02
    public_key: "{{ mainnet_sentry2_wg_public_key }}"
    endpoint: "72.60.177.106:51825"
    allowed_ips: ["10.200.5.3/32"]
    persistent_keepalive: 25
