import test from 'node:test';
import { seedLocalV2 } from './helpers/localV2.js';
import { prepareNativeDexExecution, bindSignedNativeDexExecution, verifyNativeDexExecution, submitBoundNativeDexExecution } from '../src/services/nativeDexExecution.js';
import { reconcileNativeDexBatch } from '../src/services/nativeDexMonitor.js';
import { prepareNativePayout } from '../src/services/nativePayoutDraft.js';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import pg from 'pg';
import express from 'express';
import { createNativeSourceRouter } from '../src/routes/nativeSource.js';
import { createNativeSourceIntent, bindSignedNativeSourceStep, recoverNativeSourceIntent, assertNativeSourceStepReady } from '../src/services/nativeSourceIntent.js';
import { inspectNativeSourceProgress } from '../src/services/nativeSourceRecovery.js';
import { prepareNativeSourcePlan } from '../src/services/nativeSourcePlan.js';
import { ethers } from 'ethers';
import { reviewDestinationRpc, reviewPostgres, reviewSourceRpc } from './helpers/reviewLab.js';
import { verifyAndRecordNativeSource } from '../src/services/nativeSourceSettlement.js';
import { verifyNativeSwapReadiness } from '../src/services/nativeSwapReadiness.js';
import { coordinateNativePayout } from '../src/services/nativePayoutCoordinator.js';
import { reconcileNativePayoutBatch } from '../src/services/nativePayoutMonitor.js';
import { claimNativeWalletMode } from '../src/services/nativeWalletMode.js';
import { prepareNativeRedemption, bindSignedNativeRedemption, submitBoundNativeRedemption, verifyNativeRedemption, requireNativeRedemptionEvidence } from '../src/services/nativeRedemption.js';
import { reconcileNativeRedemptionBatch } from '../src/services/nativeRedemptionMonitor.js';

// Two disposable Hardhat nodes only. No mocked chain methods or mainnet RPCs.
test('two local chains: lock, 3-of-5 release, DEX, native redemption and payout', {skip:process.env.MULTX_CROSS_CHAIN_TEST!=='1'}, async()=>{
 const {submitNativeSourceStep,submitInjectedNativeSourceStep,createNativeSourceWalletBackend}=await import('../../sdk/dist/index.js');
 const source=new ethers.JsonRpcProvider(reviewSourceRpc(),undefined,{cacheTimeout:-1});
 const dest=new ethers.JsonRpcProvider(reviewDestinationRpc(),undefined,{cacheTimeout:-1});
 const options=reviewPostgres();
 const admin=new pg.Pool(options),schema='cross_'+Date.now();let pool,server,created=false;
 try{
  for(const [rpc,id] of [[source,31337],[dest,9005]]){
   assert.match(await rpc.send('web3_clientVersion',[]),/Hardhat/i);
   assert.equal(Number((await rpc.getNetwork()).chainId),id);
  }
  const sourceWallet=ethers.Wallet.createRandom().connect(source);
  // Original wallet controls destination settlement too. The accepted bridge
  // cannot redirect its release to an unrelated operator or alter its amount.
  const destWallet=new ethers.Wallet(sourceWallet.privateKey,dest);
  for(const wallet of [sourceWallet,destWallet])await wallet.provider.send('hardhat_setBalance',[wallet.address,'0x56BC75E2D63100000']);
  const sourceSigner=new ethers.NonceManager(sourceWallet),destSigner=new ethers.NonceManager(destWallet);
  const validators=Array.from({length:5},()=>ethers.Wallet.createRandom()).sort((a,b)=>a.address.toLowerCase().localeCompare(b.address.toLowerCase()));
  const artifact=name=>JSON.parse(fs.readFileSync(new URL('../../contracts/artifacts/contracts/'+name+'.sol/'+name+'.json',import.meta.url),'utf8'));
  const deploy=async(name,args,signer)=>{const a=artifact(name),c=await new ethers.ContractFactory(a.abi,a.bytecode,signer).deploy(...args);await c.waitForDeployment();return c;};
  const sb=await deploy('MultXBridge',[validators.map(v=>v.address),3],sourceSigner);
  const db=await deploy('MultXBridge',[validators.map(v=>v.address),3],destSigner);
  const st=await deploy('MockNativeWrapper',[],sourceSigner);
  const dt=await deploy('MockERC20',['Settlement fixture','DST',18],destSigner);
  const sbAddress=(await sb.getAddress()).toLowerCase(),dbAddress=(await db.getAddress()).toLowerCase();
  const stAddress=(await st.getAddress()).toLowerCase(),dtAddress=(await dt.getAddress()).toLowerCase();
  const holder=destWallet.address.toLowerCase(),recipient=ethers.Wallet.createRandom().address.toLowerCase();
  await (await sb.addSupportedToken(stAddress)).wait();await (await sb.setSupportedRoute(stAddress,9005,true)).wait();
  const inputPolicy={enabled:true,chainId:31337,targetChains:[9005],wrapper:stAddress,bridge:sbAddress,wrapperCodeHash:ethers.keccak256(await source.getCode(stAddress)),bridgeCodeHash:ethers.keccak256(await source.getCode(sbAddress)),approvalRef:'local-native-input-only',expiresAt:Math.floor(Date.now()/1000)+3600};
  const input={sender:sourceWallet.address,amountBaseUnits:'2000',targetChain:9005};
  await assert.rejects(prepareNativeSourcePlan(source,{...inputPolicy,wrapperCodeHash:ethers.ZeroHash},input),/runtime mismatch/);
  await assert.rejects(prepareNativeSourcePlan(source,inputPolicy,{...input,targetChain:1}),/unsupported/);
  await assert.rejects(prepareNativeSourcePlan(source,{...inputPolicy,expiresAt:1},input),/approval/);
  await admin.query('CREATE SCHEMA '+schema);created=true;pool=new pg.Pool({...options,options:'-c search_path='+schema});
  for(const file of fs.readdirSync(new URL('../src/db/migrations/',import.meta.url)).filter(name=>name.endsWith('.sql')&&name>='009').sort())await pool.query(fs.readFileSync(new URL('../src/db/migrations/'+file,import.meta.url),'utf8'));
  await pool.query("INSERT INTO native_swaps(swap_id,destination_chain,recipient,minimum_output) VALUES('cross',9005,$1,2500)",[recipient]);
  const plan=await createNativeSourceIntent(pool,source,'cross',inputPolicy,input);
  await assert.rejects(createNativeSourceIntent(pool,source,'cross',inputPolicy,{...input,amountBaseUnits:'2001'}),/conflicting/);
  await assert.rejects(pool.query('DELETE FROM native_source_intents'),/immutable/);
  const audience='multx-two-chain-local-only',app=express();
  app.use('/native-source',createNativeSourceRouter({pool:{query:(...args)=>pool.query(...args),connect:()=>pool.connect()},registry:{resolve:async()=>({provider:source,policy:inputPolicy,input,confirmations:1})},audience}));
  await new Promise(resolve=>{server=app.listen(0,'127.0.0.1',resolve);});
  const baseUrl='http://127.0.0.1:'+server.address().port+'/native-source';let captured;
  const backend=createNativeSourceWalletBackend({baseUrl,audience,signer:sourceWallet,fetch:async(url,init)=>{captured={url,init};return fetch(url,init);}});
  assert.equal((await backend.getProgress('cross')).source.state,'wallet_reconciliation_required');
  assert.equal((await backend.getStep('cross',0)).kind,'wrap');
  assert.equal((await fetch(captured.url,captured.init)).status,401);
  assert.equal((await fetch(captured.url.replace('/steps/0','/steps/1'),captured.init)).status,403);
  const stranger=createNativeSourceWalletBackend({baseUrl,audience,signer:ethers.Wallet.createRandom()});
  await assert.rejects(stranger.getStep('cross',0),/403/);

  const beforeInput=await source.send('evm_snapshot',[]);
  const hashes=[null,null,null];
  assert.equal((await inspectNativeSourceProgress(source,plan,hashes,1)).state,'wallet_reconciliation_required');
  const nativeBefore=await source.getBalance(sourceWallet.address);let gas=0n,locked;
  for(const [index,{kind,...tx}] of plan.steps.entries()){
   const records=new Map();
   const store={get:async key=>records.get(key)??null,putIfAbsent:async(key,raw)=>{if(!records.has(key))records.set(key,raw);return records.get(key);}};
   let sends=0;
   const injected={provider:source,getAddress:()=>sourceWallet.getAddress(),sendTransaction:async request=>{sends++;return sourceWallet.sendTransaction(request);}};
   const submittedSource=await submitInjectedNativeSourceStep({swapId:'cross',step:index,signer:injected,backend,store});
   assert.equal(submittedSource.state,'submitted');
   await pool.end();pool=new pg.Pool({...options,options:'-c search_path='+schema});
   assert.equal((await submitInjectedNativeSourceStep({swapId:'cross',step:index,signer:injected,backend,store})).transactionHash,submittedSource.transactionHash);
   assert.equal(sends,1);
   await assert.rejects(claimNativeWalletMode(pool,'cross','raw'),/mode already fixed/);
   assert.equal((await backend.reserveAttempt('cross',index,ethers.hexlify(ethers.randomBytes(32)))).granted,false);
   const receipt=await source.getTransactionReceipt(submittedSource.transactionHash);assert.equal(receipt.status,1);
   hashes[index]=receipt.hash;gas+=receipt.gasUsed*receipt.gasPrice;if(kind==='lock')locked=receipt;
   const resumed=await recoverNativeSourceIntent(pool,source,'cross',1);
   assert.equal(resumed.state,index===2?'source_locked':'wallet_reconciliation_required');
   if(index<2)assert.equal(resumed.step,plan.steps[index+1].kind);
  }
  await assert.rejects(inspectNativeSourceProgress(source,plan,[hashes[0],hashes[0],hashes[2]],1),/duplicate/);
  await assert.rejects(inspectNativeSourceProgress(source,plan,[st.deploymentTransaction().hash,hashes[1],hashes[2]],1),/does not match/);
  assert.equal((await inspectNativeSourceProgress(source,plan,hashes,12)).state,'awaiting_finality');
  assert.equal(nativeBefore-await source.getBalance(sourceWallet.address),2000n+gas);
  assert.equal(await st.balanceOf(sourceWallet.address),0n);
  assert.equal(await st.allowance(sourceWallet.address,sbAddress),0n);
  const event=locked.logs.map(l=>{try{return sb.interface.parseLog(l);}catch{return null;}}).find(l=>l?.name==='TokensLocked');
  assert.equal(event.args.user.toLowerCase(),sourceWallet.address.toLowerCase());
  await source.send('hardhat_mine',['0xb']);
  const lock={sourceChain:31337,sourceBridge:sbAddress,sourceTxHash:event.args.txHash,sourceBlock:locked.blockNumber,sourceBlockHash:locked.blockHash,sourceToken:stAddress,user:sourceWallet.address,amount:'2000',targetChain:9005,sourceNonce:event.args.nonce.toString()};
  await (await dt.transfer(dbAddress,2000)).wait();
  const digest=ethers.solidityPackedKeccak256(['bytes32','address','address','address','uint256','uint256','uint256','uint256','address'],[lock.sourceTxHash,sbAddress,dtAddress,holder,2000,31337,lock.sourceNonce,9005,dbAddress]);
  const signatures=await Promise.all(validators.slice(0,3).map(v=>v.signMessage(ethers.getBytes(digest))));
  const releaseArgs=[dtAddress,holder,2000,31337,sbAddress,lock.sourceNonce,lock.sourceTxHash];
  await assert.rejects(db.releaseTokens.staticCall(...releaseArgs,signatures.slice(0,2)),/Insufficient signatures/);
  const released=await (await db.releaseTokens(...releaseArgs,signatures)).wait();
  await assert.rejects(db.releaseTokens.staticCall(...releaseArgs,signatures),/Nonce already processed/);
  await dest.send('hardhat_mine',['0xb','0x0']);
  await pool.query("INSERT INTO native_swap_sources(swap_id,source_chain,source_bridge,source_lock_hash,expectation) VALUES('cross',31337,$1,$2,$3)",[sbAddress,lock.sourceTxHash,lock]);
  const sourcePolicy={chainId:31337,bridgeAddress:sbAddress,confirmations:12};
  const sourceClient={provider:source,contract:new ethers.Contract(sbAddress,artifact('MultXBridge').abi,source)};
  await verifyAndRecordNativeSource(pool,'cross',sourcePolicy,sourceClient);
  const dexToken=await deploy('MockNativeWrapper',[],destSigner);
  await(await dexToken.deposit({value:2000000})).wait();
  const venue=await seedLocalV2(destSigner,dt,dexToken);
  const policy={nativeOutput:{kind:'wrapped-native-redemption',wrapper:venue.tokenOut,wrapperCodeHash:venue.tokenOutCodeHash,approvalRef:'local-redemption-fixture',confirmations:12,maxGas:'120000'},destinationDex:{venue,minimumOutput:'2500',slippageBps:50,confirmations:12,maxGas:'300000'},mode:'direct-native-payout',payoutSender:destWallet.address.toLowerCase(),custodyRef:'local-fixture-only',excludedRecipients:[],maxPayoutGas:'30000',chainId:9005,confirmations:12,bridge:dbAddress,token:dtAddress,bridgeCodeHash:ethers.keccak256(await dest.getCode(dbAddress)),sourceChain:31337,sourceBridge:sbAddress,sourceToken:stAddress,settlementHolder:holder,sourceAmountBaseUnits:'2000',settlementAmountBaseUnits:'2000',minimumNativeOutputBaseUnits:'2500',liquidityCommitmentRef:'local-backed-native-dex-fixture'};
  await pool.query("INSERT INTO native_route_policies(policy_id,policy,approval_ref,approved_by,expires_at,enabled) VALUES('local',$1,'test-only','fixture',now()+interval '1 hour',true)",[policy]);
  const expected={destinationChain:9005,transactionHash:released.hash,sourceChain:31337,sourceBridge:sbAddress,sourceLockHash:lock.sourceTxHash,token:dtAddress,holder,amount:'2000'};
  await pool.query("INSERT INTO native_swap_destinations(swap_id,policy_id,destination_chain,transaction_hash,expectation) VALUES('cross','local',9005,$1,$2)",[released.hash,expected]);
  await verifyNativeSwapReadiness(pool,'cross',sourcePolicy,sourceClient,dest);
  await assert.rejects(prepareNativePayout(pool,dest,'cross'),/DEX output required/);
  const dexPlan=await prepareNativeDexExecution(pool,dest,'cross');
  if(dexPlan.approval)await(await destSigner.sendTransaction(dexPlan.approval)).wait();
  const dexTransaction=await destWallet.populateTransaction(dexPlan.transaction);
  // This fixture exercises immutable binding and lost-broadcast recovery. Sign
  // at the approved policy ceiling so a later safety re-estimate cannot make
  // the test nondeterministically under-gassed.
  dexTransaction.gasLimit=BigInt(policy.destinationDex.maxGas);
  const dexRaw=await destWallet.signTransaction(dexTransaction);
  const dexBinding=await bindSignedNativeDexExecution(pool,'cross',dexRaw);
  assert.equal((await bindSignedNativeDexExecution(pool,'cross',dexRaw)).alreadyBound,true);
  await assert.rejects(prepareNativePayout(pool,dest,'cross'),/DEX output required/);
  const dexBefore=await dexToken.balanceOf(destWallet.address);
  let dexBroadcasts=0;
  const dexProvider=new Proxy(dest,{get(target,key){if(key==='broadcastTransaction')return async raw=>{dexBroadcasts++;await target.broadcastTransaction(raw);throw Error('lost DEX broadcast response');};const value=Reflect.get(target,key,target);return typeof value==='function'?value.bind(target):value;}});
  assert.equal((await submitBoundNativeDexExecution(pool,dexProvider,'cross',dexRaw,sourcePolicy,sourceClient)).state,'uncertain');
  assert.equal((await submitBoundNativeDexExecution(pool,dexProvider,'cross',dexRaw,sourcePolicy,sourceClient)).state,'submitted');
  assert.equal(dexBroadcasts,1);
  assert.equal((await reconcileNativeDexBatch(pool,new Map([[9005,dest]]))).results[0].state,'unverified');
  await assert.rejects(verifyNativeDexExecution(pool,dest,'cross'),/not final/);
  await dest.send('hardhat_mine',['0xb','0x0']);
  await pool.end();pool=new pg.Pool({...options,options:'-c search_path='+schema});
  assert.equal((await reconcileNativeDexBatch(pool,new Map([[9005,dest]]))).results[0].state,'dex_verified');
  assert.deepEqual((await reconcileNativeDexBatch(pool,new Map([[9005,dest]]))).results,[]);
  const dexProof=await verifyNativeDexExecution(pool,dest,'cross');
  const dexCredited=await dexToken.balanceOf(destWallet.address)-dexBefore;
  assert.equal(dexProof.evidence.transactionHash,dexBinding.transactionHash);
  assert.equal(dexProof.evidence.amount,dexCredited.toString());
  assert.ok(dexCredited>=2500n);
  assert.equal((await verifyNativeDexExecution(pool,dest,'cross')).alreadyRecorded,true);
  await assert.rejects(prepareNativePayout(pool,dest,'cross'),/native redemption required/);
  const redemptionPlan=await prepareNativeRedemption(pool,dest,'cross');
  assert.equal(redemptionPlan.amount,'2500');
  const {from:unwrapSender,...unwrapTx}=redemptionPlan.transaction;
  const redemptionRaw=await destWallet.signTransaction(unwrapTx);
  await assert.rejects(bindSignedNativeRedemption(pool,'cross',await destWallet.signTransaction({...unwrapTx,gasLimit:BigInt(unwrapTx.gasLimit)+1n})),/differs from original plan/);
  await assert.rejects(bindSignedNativeRedemption(pool,'cross',await destWallet.signTransaction({...unwrapTx,data:'0x'})),/differs from original plan/);
  assert.equal((await bindSignedNativeRedemption(pool,'cross',redemptionRaw)).alreadyBound,false);
  assert.equal((await bindSignedNativeRedemption(pool,'cross',redemptionRaw)).alreadyBound,true);
  await assert.rejects(pool.query("DELETE FROM native_redemptions WHERE swap_id='cross'"),/cannot be deleted/);
  const wrappedBefore=await dexToken.balanceOf(destWallet.address),nativeBeforeUnwrap=await dest.getBalance(destWallet.address);
  let redemptionBroadcasts=0;
  const redemptionProvider=new Proxy(dest,{get(target,key){if(key==='broadcastTransaction')return async raw=>{redemptionBroadcasts++;await target.broadcastTransaction(raw);throw Error('lost withdrawal response');};const value=Reflect.get(target,key,target);return typeof value==='function'?value.bind(target):value;}});
  const redemptionSubmitted=await submitBoundNativeRedemption(pool,redemptionProvider,'cross',redemptionRaw);
  assert.equal(redemptionSubmitted.state,'uncertain');
  assert.equal((await submitBoundNativeRedemption(pool,redemptionProvider,'cross',redemptionRaw)).state,'submitted');
  assert.equal(redemptionBroadcasts,1);
  await assert.rejects(verifyNativeRedemption(pool,dest,'cross'),/not final/);
  await assert.rejects(prepareNativePayout(pool,dest,'cross'),/native redemption required/);
  const unwrapReceipt=await dest.getTransactionReceipt(redemptionSubmitted.transactionHash);
  assert.equal(wrappedBefore-await dexToken.balanceOf(destWallet.address),2500n);
  assert.equal(await dest.getBalance(destWallet.address)-nativeBeforeUnwrap+unwrapReceipt.gasUsed*unwrapReceipt.gasPrice,2500n);
  await dest.send('hardhat_mine',['0xb','0x0']);
  await pool.end();pool=new pg.Pool({...options,options:'-c search_path='+schema});
  assert.equal((await reconcileNativeRedemptionBatch(pool,new Map([[9005,dest]]))).results[0].state,'redemption_verified');
  assert.deepEqual((await reconcileNativeRedemptionBatch(pool,new Map([[9005,dest]]))).results,[]);
  assert.equal((await verifyNativeRedemption(pool,dest,'cross')).alreadyRecorded,true);
  const reorganizedRedemptionProvider=new Proxy(dest,{get(target,key){
    if(key==='getBlock')return async height=>height===unwrapReceipt.blockNumber?{hash:ethers.ZeroHash}:target.getBlock(height);
    const value=Reflect.get(target,key,target);return typeof value==='function'?value.bind(target):value;
  }});
  await assert.rejects(requireNativeRedemptionEvidence(pool,reorganizedRedemptionProvider,'cross',policy),/no longer canonical/);
  await assert.rejects(prepareNativePayout(pool,reorganizedRedemptionProvider,'cross'),/no longer canonical/);
  await assert.rejects(verifyNativeRedemption(pool,reorganizedRedemptionProvider,'cross'),/redemption reorg/);
  await assert.rejects(prepareNativePayout(pool,{getNetwork:()=>dest.getNetwork(),getBlockNumber:()=>dest.getBlockNumber(),getBlock:async()=>({hash:ethers.ZeroHash})},'cross'),/no longer canonical/);

  let signed;
  const custody={custodyRef:policy.custodyRef,getSignedTransaction:async request=>{if(!signed){const {from,...tx}=request.transaction;signed=await destWallet.signTransaction(tx);}return signed;}};
  const args={pool,provider:dest,swapId:'cross',custody,sourcePolicy,sourceClient,submit:true};
  const submitted=await coordinateNativePayout(args);assert.equal(submitted.state,'submitted');
  assert.equal((await coordinateNativePayout(args)).transactionHash,submitted.transactionHash);
  assert.equal((await reconcileNativePayoutBatch(pool,new Map([[9005,dest]]))).results[0].state,'unverified');
  await dest.send('hardhat_mine',['0xb','0x0']);
  assert.equal((await reconcileNativePayoutBatch(pool,new Map([[9005,dest]]))).results[0].state,'completed');
  assert.equal(await dest.getBalance(recipient),2500n);
  assert.equal(await dt.balanceOf(holder),1000000n*10n**18n-1000000n-2000n);
  assert.equal(await st.balanceOf(sbAddress),2000n);
  assert.equal((await pool.query("SELECT count(*)::int AS n FROM native_payout_assignments WHERE state='verified'")).rows[0].n,1);
  const finalProgress=await backend.getProgress('cross');assert.equal(finalProgress.source.state,'source_locked');assert.equal(finalProgress.swapState,'completed');
  assert.equal(await source.send('evm_revert',[beforeInput]),true);
  assert.equal((await inspectNativeSourceProgress(source,plan,hashes,1)).state,'pending_or_unknown');
 }finally{if(server){server.closeAllConnections();await new Promise(resolve=>server.close(resolve));}if(pool)await pool.end();if(created)await admin.query('DROP SCHEMA '+schema+' CASCADE');await admin.end();source.destroy();dest.destroy();}
});
