import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import pg from 'pg';
import { reviewPostgres } from './helpers/reviewLab.js';
import { assignNativePayout, verifyAndRecordNativePayout } from '../src/services/nativePayoutStore.js';
import { verifyAndRecordNativeSource } from '../src/services/nativeSourceSettlement.js';
const a=n=>'0x'+n.toString(16).padStart(40,'0'),h=n=>'0x'+n.toString(16).padStart(64,'0');
test('PostgreSQL payout ownership, concurrency and reconnect recovery',{skip:process.env.MULTX_PAYOUT_DB_TEST!=='1'},async()=>{
 // Fixed disposable endpoint. Separate random schema; no production DB configuration.
 const options=reviewPostgres();
 const admin=new pg.Pool(options),schema='payout_'+Date.now();let pool;
 try{
  await admin.query('CREATE SCHEMA '+schema);
  pool=new pg.Pool({...options,options:'-c search_path='+schema});
  await pool.query(fs.readFileSync(new URL('../src/db/migrations/009-native-payout-assignments.sql',import.meta.url),'utf8'));
  await pool.query(fs.readFileSync(new URL('../src/db/migrations/010-native-swap-completion.sql',import.meta.url),'utf8'));
  await pool.query(fs.readFileSync(new URL('../src/db/migrations/011-native-source-evidence.sql',import.meta.url),'utf8'));
  const expected={mode:'direct-native',swapId:'swap-1',chainId:9005,transactionHash:h(1),sender:a(100000),recipient:a(200000),nonce:7,minimumOutputBaseUnits:'1000',confirmations:12};
  await assert.rejects(assignNativePayout(pool,expected),/not eligible/);
  for(const id of ['swap-1','swap-2'])await pool.query("INSERT INTO native_swaps(swap_id,destination_chain,recipient,minimum_output,settlement_evidence_ref,route_policy_ref) VALUES($1,9005,$2,1000,'synthetic-settlement','synthetic-policy')",[id,expected.recipient]);
  await assert.rejects(assignNativePayout(pool,expected),/not eligible/);
  await assert.rejects(pool.query("INSERT INTO native_swaps(swap_id,destination_chain,recipient,minimum_output,state,settlement_evidence_ref,route_policy_ref,completed_at) VALUES('bypass',9005,$1,1000,'completed','x','y',now())",[expected.recipient]),/must await settlement/);
  await assert.rejects(pool.query("UPDATE native_swaps SET state='payout_ready'"),/verified source required/);
  const source={chainId:1,bridgeAddress:a(500000),confirmations:12};
  const lock={sourceChain:1,sourceBridge:source.bridgeAddress,sourceTxHash:h(10),sourceBlock:50,sourceBlockHash:h(20),sourceToken:a(600000),user:a(700000),amount:'1000',targetChain:9005,sourceNonce:'1'};
  await pool.query('INSERT INTO native_swap_sources(swap_id,source_chain,source_bridge,source_lock_hash,expectation) VALUES($1,1,$2,$3,$4)', ['swap-1',source.bridgeAddress,h(10),lock]);
  await assert.rejects(pool.query('INSERT INTO native_swap_sources(swap_id,source_chain,source_bridge,source_lock_hash,expectation) VALUES($1,1,$2,$3,$4)', ['swap-2',source.bridgeAddress,h(10),lock]),e=>e.code==='23505');
  const event={removed:false,blockNumber:50,blockHash:h(20),address:source.bridgeAddress,args:{txHash:h(10),token:lock.sourceToken,user:lock.user,amount:'1000',targetChain:9005,nonce:'1'}};
  const sourceClient={provider:{getNetwork:async()=>({chainId:1n}),getBlockNumber:async()=>61,getBlock:async()=>({hash:h(20)})},contract:{filters:{TokensLocked:()=>({})},queryFilter:async()=>[event]}};
  event.removed=true;
  await assert.rejects(verifyAndRecordNativeSource(pool,'swap-1',source,sourceClient),/removed/);
  assert.equal((await pool.query("SELECT verified_evidence FROM native_swap_sources WHERE swap_id='swap-1'")).rows[0].verified_evidence,null);
  event.removed=false;
  assert.equal((await verifyAndRecordNativeSource(pool,'swap-1',source,sourceClient)).alreadyRecorded,false);
  assert.equal((await verifyAndRecordNativeSource(pool,'swap-1',source,sourceClient)).alreadyRecorded,true);
  assert.equal((await pool.query("SELECT state FROM native_swaps WHERE swap_id='swap-1'")).rows[0].state,'awaiting_settlement');
  sourceClient.provider.getBlock=async()=>({hash:h(21)});
  await assert.rejects(verifyAndRecordNativeSource(pool,'swap-1',source,sourceClient),/canonical/);
  sourceClient.provider.getBlock=async()=>({hash:h(20)});
  const lock2={...lock,sourceTxHash:h(11)};
  await pool.query('INSERT INTO native_swap_sources(swap_id,source_chain,source_bridge,source_lock_hash,expectation) VALUES($1,1,$2,$3,$4)', ['swap-2',source.bridgeAddress,h(11),lock2]);
  event.args.txHash=h(11);
  await verifyAndRecordNativeSource(pool,'swap-2',source,sourceClient);
  await pool.query("UPDATE native_swaps SET state='payout_ready'");
  assert.deepEqual(await assignNativePayout(pool,expected),expected);
  assert.deepEqual(await assignNativePayout(pool,expected),expected);
  await assert.rejects(assignNativePayout(pool,{...expected,recipient:a(300000)}),/terms do not match|conflicting/);
  await assert.rejects(assignNativePayout(pool,{...expected,swapId:'swap-2'}),e=>e.code==='23505');
  await assert.rejects(assignNativePayout(pool,{...expected,swapId:'swap-2',transactionHash:h(3)}),e=>e.code==='23505');
  await assert.rejects(pool.query("UPDATE native_payout_assignments SET recipient=$1 WHERE swap_id='swap-1'",[a(400000)]),/immutable/);
  const tx={hash:h(1),from:expected.sender,to:expected.recipient,nonce:7,data:'0x',value:1000n,blockNumber:50,blockHash:h(2)};
  let verifications=0;
  const provider={getNetwork:async()=>{verifications++;return {chainId:9005n};},getTransaction:async()=>tx,getTransactionReceipt:async()=>({hash:h(1),status:1,blockNumber:50,blockHash:h(2)}),getBlockNumber:async()=>61,getBlock:async()=>({hash:h(2)}),getCode:async()=> '0x',getBalance:async(_,height)=>height===49?500n:1500n};
  await assert.rejects(verifyAndRecordNativePayout(pool,{...provider,getBlockNumber:async()=>50},'swap-1'),/not final/);
  assert.equal((await pool.query("SELECT state FROM native_payout_assignments WHERE swap_id='swap-1'")).rows[0].state,'assigned');
  // A DB failure after payout verification must roll back both records.
  await pool.query("CREATE FUNCTION fail_completion_test() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'injected completion failure'; END $$; CREATE TRIGGER fail_completion BEFORE UPDATE ON native_swaps FOR EACH ROW EXECUTE FUNCTION fail_completion_test()");
  await assert.rejects(verifyAndRecordNativePayout(pool,provider,'swap-1'),/injected completion failure/);
  assert.equal((await pool.query("SELECT state FROM native_payout_assignments WHERE swap_id='swap-1'")).rows[0].state,'assigned');
  assert.equal((await pool.query("SELECT state FROM native_swaps WHERE swap_id='swap-1'")).rows[0].state,'payout_ready');
  await pool.query('DROP TRIGGER fail_completion ON native_swaps');
  verifications=0;
  const outcomes=await Promise.all(Array.from({length:6},()=>verifyAndRecordNativePayout(pool,provider,'swap-1')));
  assert.equal(outcomes.filter(o=>!o.alreadyRecorded).length,1);assert.equal(verifications,1);
  const evidence=outcomes[0].evidence;
  assert.equal((await pool.query("SELECT state FROM native_swaps WHERE swap_id='swap-1'")).rows[0].state,'completed');
  await assert.rejects(pool.query("UPDATE native_swaps SET state='completed',completed_at=now() WHERE swap_id='swap-2'"),/verified matching/);
  await pool.end();pool=new pg.Pool({...options,options:'-c search_path='+schema});
  const retried=await verifyAndRecordNativePayout(pool,{},'swap-1');assert(retried.alreadyRecorded);assert.deepEqual(retried.evidence,evidence);
  await assert.rejects(pool.query("UPDATE native_payout_assignments SET state='assigned',evidence=NULL,verified_at=NULL WHERE swap_id='swap-1'"),/immutable/);
  await assert.rejects(pool.query("DELETE FROM native_payout_assignments WHERE swap_id='swap-1'"),/cannot be deleted/);
  assert.equal((await pool.query('SELECT count(*)::int AS n FROM native_payout_assignments')).rows[0].n,1);
 }finally{if(pool)await pool.end();await admin.query('DROP SCHEMA '+schema+' CASCADE');await admin.end();}
});
