/**
 * @lithosphere/sdk
 *
 * High-level client for the Lithosphere chain. Pair with `viem` / `ethers` for
 * contract writes; the ABIs you need ship from `@lithosphere/blockchain-core`.
 */

export { LithoClient } from './client.js';

// Re-export the most-used primitives so consumers can do a single install:
//   import { LithoClient, NETWORKS, LEP100_ABI, LithoError } from '@lithosphere/sdk';
export {
  ErrorCode,
  LithoError,
  NETWORKS,
  LEP100_ABI,
  LITHONATIVE_ABI,
  WLITHO_ABI,
  getNetwork,
  isNetworkName,
  type AccountBalance,
  type CallOptions,
  type ClientConfig,
  type Log,
  type NetworkConfig,
  type NetworkName,
  type RetryConfig,
  type SendOptions,
  type TokenBalance,
  type TransactionReceipt,
  type TransactionResponse,
  type TransactionStatus,
} from '@lithosphere/blockchain-core';

export const SDK_VERSION = '0.1.0';

/**
 * REST-API path/method/response types, auto-generated from
 * `docs/api-reference/openapi.yaml`. Pair with `openapi-fetch` for a typed
 * runtime client, or use the `paths` interface directly with your own fetcher.
 *
 * Example:
 *
 *   import type { paths } from '@lithosphere/sdk';
 *   type BlocksResp = paths['/blocks']['get']['responses']['200']['content']['application/json'];
 *
 * Regenerated by CI via `pnpm --filter @lithosphere/sdk codegen:openapi`.
 */
export type { paths, components, operations } from './generated/openapi.js';
